-- @description Composition Studio
-- @version 0.4-test4
-- @author Klangwerke
-- @about Dockable AI chat, controlled REAPER actions and MIDI composition.

local SCRIPT_NAME="Composition Studio"
local VERSION="0.4-test4"
local EXT_SECTION,EXT_KEY="CompositionStudio","OpenAIAPIKey"
local WINDOW_STATE_KEY,HISTORY_KEY="WindowOpen","HistoryV1"
local UPDATE_URL="https://raw.githubusercontent.com/wibem1/Reaper-Composition/composition-studio/Composition%20Studio.lua"
local SCRIPT_PATH=(debug.getinfo(1,"S").source or ""):gsub("^@","")

local function ensure_native_startup_hook()
 local p=reaper.GetResourcePath().."/Scripts/__startup.lua"; local mark="-- BEGIN COMPOSITION STUDIO AUTO START"
 local f=io.open(p,"rb"); local old=f and (f:read("*a") or "") or ""; if f then f:close() end
 if old:find(mark,1,true) then return end
 local block=[[
-- BEGIN COMPOSITION STUDIO AUTO START
do
 if reaper.GetExtState("CompositionStudio","WindowOpen")=="1" then
  local p=reaper.GetResourcePath().."/Scripts/Composition Studio/Composition Studio.lua"
  local f=io.open(p,"rb")
  if f then f:close(); local ok,e=pcall(dofile,p); if not ok then reaper.ShowConsoleMsg(tostring(e).."\n") end end
 end
end
-- END COMPOSITION STUDIO AUTO START
]]
 local w=io.open(p,"wb"); if w then if old~="" and old:sub(-1)~="\n" then old=old.."\n" end; w:write(old..block); w:close() end
end
ensure_native_startup_hook()
if type(reaper.ImGui_CreateContext)~="function" then reaper.ShowMessageBox("Composition Studio benötigt ReaImGui.",SCRIPT_NAME,0); return end
local ctx=reaper.ImGui_CreateContext(SCRIPT_NAME,reaper.ImGui_ConfigFlags_DockingEnable())
if type(reaper.ImGui_SetConfigVar)=="function" and type(reaper.ImGui_ConfigVar_DockingNoSplit)=="function" then reaper.ImGui_SetConfigVar(ctx,reaper.ImGui_ConfigVar_DockingNoSplit(),1) end
reaper.SetExtState(EXT_SECTION,WINDOW_STATE_KEY,"1",true)
local open,input,busy=true,"",false; local last_diag={}; local restarting=false; local update_status=""; local history={}; local chat_start=1; local info_visible=false; local history_mode=false; local current_project=reaper.EnumProjects(-1,""); local font=nil
if type(reaper.ImGui_CreateFont)=="function" then local ok,f=pcall(reaper.ImGui_CreateFont,"sans-serif"); if ok then font=f end end
if font and type(reaper.ImGui_Attach)=="function" then pcall(reaper.ImGui_Attach,ctx,font) end
local function push_font() if not font then return false end; return pcall(reaper.ImGui_PushFont,ctx,font,18) end
local function pop_font(x) if x then reaper.ImGui_PopFont(ctx) end end
local function trim(s) return (s or ""):gsub("^%s+",""):gsub("%s+$","") end
local function shell_quote(s) return "'"..tostring(s):gsub("'","'\\''").."'" end
local function json_escape(s) return tostring(s or ""):gsub("\\","\\\\"):gsub('"','\\"'):gsub("\n","\\n"):gsub("\r","\\r"):gsub("\t","\\t") end
local function read_file(p) local f=io.open(p,"rb"); if not f then return nil end; local s=f:read("*a"); f:close(); return s end
local function write_file(p,s) local f=io.open(p,"wb"); if not f then return false end; f:write(s); f:close(); return true end
local function version_parts(v) local a,b,t=v:match("^(%d+)%.(%d+)%-test(%d+)$"); return tonumber(a),tonumber(b),tonumber(t) end
local function version_is_newer(r,l) local a,b,c=version_parts(r); local x,y,z=version_parts(l); if not(a and x) then return false end; if a~=x then return a>x end; if b~=y then return b>y end; return c>z end
local function install_update()
 if busy then return end; busy=true; update_status="Update wird geladen …"; local tmp=os.tmpname()..".lua"; local code=os.tmpname()..".code"; local url=UPDATE_URL.."?version_check="..tostring(os.time())
 os.execute("/usr/bin/curl -sS -L --max-time 60 -o "..shell_quote(tmp).." -w '%{http_code}' "..shell_quote(url).." > "..shell_quote(code))
 local status=trim(read_file(code)); local fresh=read_file(tmp); os.remove(code); os.remove(tmp)
 if status~="200" or not fresh or #fresh<1000 then update_status="Update fehlgeschlagen (HTTP "..tostring(status)..")."; busy=false; return end
 local rv=fresh:match("%-%- @version%s+([%w%.%-]+)"); if not rv or not fresh:find('local SCRIPT_NAME="Composition Studio"',1,true) then update_status="Update abgebrochen: heruntergeladene Datei ist ungültig."; busy=false; return end
 if rv==VERSION then update_status="Bereits aktuell: "..VERSION; busy=false; return end
 if not version_is_newer(rv,VERSION) then update_status="Kein neueres Update verfügbar. Lokal: "..VERSION..", GitHub: "..rv; busy=false; return end
 if SCRIPT_PATH=="" or not write_file(SCRIPT_PATH,fresh) then update_status="Update konnte nicht installiert werden."; busy=false; return end
 update_status="Update auf "..rv.." installiert. Neustart …"; restarting=true; open=false; reaper.SetExtState(EXT_SECTION,WINDOW_STATE_KEY,"1",true); reaper.defer(function() local ok,e=pcall(dofile,SCRIPT_PATH); if not ok then reaper.ShowConsoleMsg("Composition Studio Update-Neustart: "..tostring(e).."\n") end end)
end
local function utf8(cp) if cp<=0x7f then return string.char(cp) elseif cp<=0x7ff then return string.char(0xc0+math.floor(cp/64),0x80+cp%64) elseif cp<=0xffff then return string.char(0xe0+math.floor(cp/4096),0x80+math.floor(cp/64)%64,0x80+cp%64) else return string.char(0xf0+math.floor(cp/262144),0x80+math.floor(cp/4096)%64,0x80+cp%64) end end
local function read_json_string(raw,q) local out,i={},q+1; while i<=#raw do local c=raw:sub(i,i); if c=='"' then return table.concat(out) end; if c=="\\" then i=i+1; local e=raw:sub(i,i); if e=="n" then out[#out+1]="\n" elseif e=="r" then out[#out+1]="\r" elseif e=="t" then out[#out+1]="\t" elseif e=='"' then out[#out+1]='"' elseif e=="\\" then out[#out+1]="\\" elseif e=="u" then local h=raw:sub(i+1,i+4); local cp=tonumber(h,16); if cp then i=i+4; out[#out+1]=utf8(cp) end else out[#out+1]=e end else out[#out+1]=c end; i=i+1 end; return table.concat(out) end
local function response_text(raw) local s,e=raw:find('"type"%s*:%s*"output_text"'); if not s then return nil end; local ts,te=raw:find('"text"%s*:',e+1); if not ts then return nil end; local q=raw:find('"',te+1,true); return q and read_json_string(raw,q) or nil end
local function get_key() local k=trim(reaper.GetExtState(EXT_SECTION,EXT_KEY)); if k~="" then return k end; local ok,v=reaper.GetUserInputs(SCRIPT_NAME.." – Ersteinrichtung",1,"OpenAI API-Key:,extrawidth=320",""); if not ok then return nil end; k=trim(v); if k~="" then reaper.SetExtState(EXT_SECTION,EXT_KEY,k,true); return k end end
local function diag_set(k,v) last_diag[k]=v end
local function diag_json()
 local keys={"version","request","context","controller_prompt","controller_answer","composition_prompt","composition_answer","apply_result","halion_result"}; local a={"{\n  \"timestamp\": \""..json_escape(os.date("%Y-%m-%dT%H:%M:%S")).."\""}
 for _,k in ipairs(keys) do a[#a+1]=",\n  \""..k.."\": \""..json_escape(last_diag[k] or "").."\"" end; a[#a+1]="\n}\n"; return table.concat(a)
end
local function save_diagnosis()
 local dir=reaper.GetResourcePath().."/Composition Studio Diagnosen"; reaper.RecursiveCreateDirectory(dir,0); local fn=dir.."/Composition-Studio-Diagnose-"..os.date("%Y%m%d-%H%M%S")..".json"
 if write_file(fn,diag_json()) then update_status="Diagnose gespeichert: "..fn else update_status="Diagnose konnte nicht gespeichert werden." end
end
local function run_openai(prompt,key) local b=os.tmpname(); local rq,rs,cd=b..".json",b..".out",b..".code"; if not write_file(rq,'{"model":"gpt-5.6","input":"'..json_escape(prompt)..'"}') then return nil,"Anfrage konnte nicht geschrieben werden." end; os.execute("/usr/bin/curl -sS --max-time 120 -o "..shell_quote(rs).." -w '%{http_code}' -H "..shell_quote("Authorization: Bearer "..key).." -H 'Content-Type: application/json' --data-binary @"..shell_quote(rq).." https://api.openai.com/v1/responses > "..shell_quote(cd)); local status=trim(read_file(cd)); local raw=read_file(rs); os.remove(rq); os.remove(rs); os.remove(cd); if status~="200" or not raw then return nil,"KI-Aufruf fehlgeschlagen (HTTP "..tostring(status)..")." end; return response_text(raw),nil end
local function enc(s) return (tostring(s or ""):gsub("([^%w%-%._~])",function(c) return string.format("%%%02X",string.byte(c)) end)) end
local function dec(s) return (tostring(s or ""):gsub("%%(%x%x)",function(h) return string.char(tonumber(h,16)) end)) end
local function save_history(proj) proj=proj or current_project; if not proj then return end; local rows={}; for _,m in ipairs(history) do rows[#rows+1]=enc(m.role).."\t"..enc(m.text) end; reaper.SetProjExtState(proj,EXT_SECTION,HISTORY_KEY,table.concat(rows,"\n")) end
local function load_history(proj) history={}; if proj then local _,raw=reaper.GetProjExtState(proj,EXT_SECTION,HISTORY_KEY); if raw and raw~="" then for row in raw:gmatch("[^\n]+") do local r,t=row:match("^([^\t]*)\t(.*)$"); if r then history[#history+1]={role=dec(r),text=dec(t)} end end end end; if #history==0 then history={{role="KI",text="Composition Studio ist bereit."}} end; chat_start=1; info_visible=false; history_mode=false end
local function add(role,text) history[#history+1]={role=role,text=text}; save_history() end
local function clear_saved_history() history={{role="KI",text="Composition Studio ist bereit."}}; chat_start=1; info_visible=false; history_mode=false; save_history() end
load_history(current_project)
local function item_guid(item) local ok,g=reaper.GetSetMediaItemInfo_String(item,"GUID","",false); return ok and g or "" end
local function track_guid(track) return reaper.GetTrackGUID(track) or "" end
local function selected_tracks() local a={}; for i=0,reaper.CountSelectedTracks(0)-1 do local tr=reaper.GetSelectedTrack(0,i); local _,n=reaper.GetTrackName(tr); a[#a+1]={track=tr,guid=track_guid(tr),name=n~="" and n or "Unbenannte Spur",index=math.floor(reaper.GetMediaTrackInfo_Value(tr,"IP_TRACKNUMBER"))} end; return a end
local function selected_items(with_notes) local a={}; for i=0,reaper.CountSelectedMediaItems(0)-1 do local item=reaper.GetSelectedMediaItem(0,i); local take=item and reaper.GetActiveTake(item); if take and reaper.TakeIsMIDI(take) then local tr=reaper.GetMediaItem_Track(item); local _,tn=reaper.GetTrackName(tr); local _,kn=reaper.GetSetMediaItemTakeInfo_String(take,"P_NAME","",false); local pos=reaper.GetMediaItemInfo_Value(item,"D_POSITION"); local len=reaper.GetMediaItemInfo_Value(item,"D_LENGTH"); local it={item=item,take=take,track=tr,guid=item_guid(item),track_guid=track_guid(tr),track_name=tn~="" and tn or "Unbenannte Spur",take_name=kn~="" and kn or "Unbenanntes MIDI-Item",start_qn=reaper.TimeMap2_timeToQN(0,pos),end_qn=reaper.TimeMap2_timeToQN(0,pos+len),notes={}}; if with_notes then local _,ncount=reaper.MIDI_CountEvts(take); for n=0,(ncount or 0)-1 do local ok,_,muted,s,e,ch,p,v=reaper.MIDI_GetNote(take,n); if ok and not muted then local st=reaper.MIDI_GetProjTimeFromPPQPos(take,s); local et=reaper.MIDI_GetProjTimeFromPPQPos(take,e); local sq=reaper.TimeMap2_timeToQN(0,st); local eq=reaper.TimeMap2_timeToQN(0,et); it.notes[#it.notes+1]={start_qn=sq,duration_qn=eq-sq,pitch=p,velocity=v,channel=ch} end end end; a[#a+1]=it end end; return a end
local function track_context_items(tracks) local a={}; local seen={}; for _,t in ipairs(tracks) do for i=0,reaper.CountTrackMediaItems(t.track)-1 do local item=reaper.GetTrackMediaItem(t.track,i); local take=item and reaper.GetActiveTake(item); if take and reaper.TakeIsMIDI(take) then local g=item_guid(item); if not seen[g] then seen[g]=true; local _,kn=reaper.GetSetMediaItemTakeInfo_String(take,"P_NAME","",false); local pos=reaper.GetMediaItemInfo_Value(item,"D_POSITION"); local len=reaper.GetMediaItemInfo_Value(item,"D_LENGTH"); local it={item=item,take=take,track=t.track,guid=g,track_guid=t.guid,track_name=t.name,take_name=kn~="" and kn or "Unbenanntes MIDI-Item",start_qn=reaper.TimeMap2_timeToQN(0,pos),end_qn=reaper.TimeMap2_timeToQN(0,pos+len),notes={}}; local _,nc=reaper.MIDI_CountEvts(take); for n=0,(nc or 0)-1 do local ok,_,muted,s,e,ch,p,v=reaper.MIDI_GetNote(take,n); if ok and not muted then local st=reaper.MIDI_GetProjTimeFromPPQPos(take,s); local et=reaper.MIDI_GetProjTimeFromPPQPos(take,e); local sq=reaper.TimeMap2_timeToQN(0,st); local eq=reaper.TimeMap2_timeToQN(0,et); it.notes[#it.notes+1]={start_qn=sq,duration_qn=eq-sq,pitch=p,velocity=v,channel=ch} end end; a[#a+1]=it end end end end; return a end
local function time_selection_context() local s,e=reaper.GetSet_LoopTimeRange(false,false,0,0,false); if not s or not e or e<=s then return "TIME_SELECTION none" end; local sq=reaper.TimeMap2_timeToQN(0,s); local eq=reaper.TimeMap2_timeToQN(0,e); local _,sm,sb=reaper.TimeMap2_timeToBeats(0,s); local _,em,eb=reaper.TimeMap2_timeToBeats(0,e); return string.format("TIME_SELECTION startQN=%.3f endQN=%.3f startBar=%d startBeat=%.3f endBar=%d endBeat=%.3f",sq,eq,(sm or 0)+1,(sb or 0)+1,(em or 0)+1,(eb or 0)+1) end
local function compact_context(items,tracks) tracks=tracks or selected_tracks(); local l={string.format("Tempo %.2f BPM; selected MIDI items=%d; selected tracks=%d",reaper.Master_GetTempo(),#items,#tracks),time_selection_context()}; for i,t in ipairs(tracks) do l[#l+1]=string.format("TRACK %d id=%s name=%s index=%d",i,t.guid,t.name,t.index) end; for i,it in ipairs(items) do l[#l+1]=string.format("ITEM %d id=%s trackId=%s track=%s take=%s rangeQN=%.3f..%.3f",i,it.guid,it.track_guid,it.track_name,it.take_name,it.start_qn,it.end_qn) end; return table.concat(l,"\n") end
local function music_context(items,tracks) local l={compact_context(items,tracks)}; for _,it in ipairs(items) do for _,n in ipairs(it.notes) do l[#l+1]=string.format("N %s %.5f %.5f %d %d %d",it.guid,n.start_qn,n.duration_qn,n.pitch,n.velocity,n.channel) end end; return table.concat(l,"\n") end
local function recent_dialog() local l={}; for i=math.max(1,#history-7),#history do l[#l+1]=history[i].role..": "..history[i].text end; return table.concat(l,"\n") end

local function first_program_changes_on_track(track)
 local pcs={}
 for i=0,reaper.CountTrackMediaItems(track)-1 do local item=reaper.GetTrackMediaItem(track,i); local take=item and reaper.GetActiveTake(item); if take and reaper.TakeIsMIDI(take) then local _,_,cc=reaper.MIDI_CountEvts(take); for n=0,(cc or 0)-1 do local ok,_,muted,ppq,chanmsg,ch,msg2=reaper.MIDI_GetCC(take,n); if ok and not muted and chanmsg==0xC0 then local tm=reaper.MIDI_GetProjTimeFromPPQPos(take,ppq); local c=(ch or 0)+1; if not pcs[c] or tm<pcs[c].time then pcs[c]={program=msg2,time=tm} end end end end end
 return pcs
end
local function find_halions(track) local out={}; for fx=0,reaper.TrackFX_GetCount(track)-1 do local ok,n=reaper.TrackFX_GetFXName(track,fx,""); if ok and (n or ""):lower():find("halion sonic",1,true) then out[#out+1]=fx end end; return out end
local function halion_program_param(track,fx,ch) local wanted="S"..ch.." Program Change"; for p=0,reaper.TrackFX_GetNumParams(track,fx)-1 do local ok,n=reaper.TrackFX_GetParamName(track,fx,p,""); if ok and n==wanted then return p end end end
local function source_tracks_for_halion(dest)
 local out,seen={},{}
 if reaper.CountTrackMediaItems(dest)>0 then out[#out+1]=dest; seen[dest]=true end
 for r=0,reaper.GetTrackNumSends(dest,-1)-1 do local src=reaper.GetTrackSendInfo_Value(dest,-1,r,"P_SRCTRACK"); if src and not seen[src] then out[#out+1]=src; seen[src]=true end end
 return out
end
local function initialize_halion_track(track)
 local fxs=find_halions(track); if #fxs==0 then return 0 end; local pcs={}
 for _,src in ipairs(source_tracks_for_halion(track)) do local found=first_program_changes_on_track(src); for ch,v in pairs(found) do if not pcs[ch] or v.time<pcs[ch].time then pcs[ch]=v end end end
 local changed=0; for _,fx in ipairs(fxs) do for ch=1,16 do local v=pcs[ch]; if v then local p=halion_program_param(track,fx,ch); if p then reaper.TrackFX_SetParamNormalized(track,fx,p,v.program/127.0); changed=changed+1 end end end end; return changed
end
local function initialize_halion_project() local tracks,slots=0,0; for i=0,reaper.CountTracks(0)-1 do local tr=reaper.GetTrack(0,i); if #find_halions(tr)>0 then local n=initialize_halion_track(tr); if n>0 then tracks=tracks+1; slots=slots+n end end end; return tracks,slots end

local CONTROLLER=[[Du bist der Controller von Composition Studio in REAPER. Der Benutzer spricht frei; es gibt KEINE Triggerwörter. Interpretiere nur, was eindeutig gemeint ist. Bei Unklarheit FRAGE nach.
Antworte mit GENAU EINER Zeile:
CHAT|Text
ASK|Rückfrage
ACTION|TRANSPOSE|ITEM_GUID|SEMITONES|Beschreibung
ACTION|MOVE_ITEM|ITEM_GUID|DELTA_QN|Beschreibung
ACTION|COPY_ITEM|ITEM_GUID|DELTA_QN|Beschreibung
ACTION|RENAME_TRACK|TRACK_GUID|NEUER_NAME|Beschreibung
ACTION|INIT_HALION|-|-|Beschreibung
NEED_ANALYSIS|Begründung
NEED_MUSIC|Begründung\nNEED_NEW|Begründung
Nur angebotene IDs verwenden. Wenn der Benutzer HALion Sonic aus vorhandenen Program Changes initialisieren, vorbereiten oder die Instrumentierung übernehmen lassen will, verwende ACTION|INIT_HALION|-|-|Beschreibung. Diese Aktion setzt die HALion-Programmparameter einmalig und erzeugt keine dauerhaften MIDI-Links. Eine ausgewählte TRACK_GUID kann auch ohne ausgewähltes MIDI-Item das Ziel eines musikalischen Auftrags sein. TIME_SELECTION ist der markierte Zielbereich. Eine vollständige Neukomposition benötigt weder ein vorhandenes MIDI-Item noch eine ausgewählte Spur. Vorhandene REAPER-Auswahl und TIME_SELECTION sind nur Kontext, solange der Benutzer nicht sprachlich auf vorhandenes Material, Auswahl, Spur, Item, markierten Bereich, Fortsetzung oder Bearbeitung Bezug nimmt. Ein klarer eigenständiger Auftrag wie 'Erstelle ein Stück für Violine und Gitarre' ist NEED_NEW. Für Analyse des Notenmaterials: NEED_ANALYSIS. Für Komposition, Variation, Fortsetzung, Ergänzung oder musikalische Bearbeitung mit neuem MIDI: NEED_MUSIC. Für normale Unterhaltung: CHAT.]]
local function parse_action(line,items) line=trim(line or ""); local typ,a,b,desc=line:match("^ACTION|([^|]+)|([^|]+)|([^|]+)|(.+)$"); if not typ then return nil,"Ungültiger ACTION-Aufruf." end; local bi,bt={},{}; for _,it in ipairs(items) do bi[it.guid]=it; bt[it.track_guid]=it.track end; for _,t in ipairs(selected_tracks()) do bt[t.guid]=t.track end; if typ=="INIT_HALION" then return {kind=typ,desc=desc} elseif typ=="TRANSPOSE" then local n=tonumber(b); if not bi[a] or not n or n~=math.floor(n) or n< -127 or n>127 then return nil,"Ungültige Transposition." end; return {kind=typ,item=bi[a],n=n,desc=desc} elseif typ=="MOVE_ITEM" or typ=="COPY_ITEM" then local q=tonumber(b); if not bi[a] or not q then return nil,"Ungültige Item-Verschiebung." end; return {kind=typ,item=bi[a],q=q,desc=desc} elseif typ=="RENAME_TRACK" then if not bt[a] or trim(b)=="" then return nil,"Ungültige Spurbenennung." end; return {kind=typ,track=bt[a],name=trim(b),desc=desc} end; return nil,"Diese Aktion ist nicht freigegeben." end
local function execute_action(a) reaper.Undo_BeginBlock2(0); local ok,err=xpcall(function() if a.kind=="INIT_HALION" then local tr,sl=initialize_halion_project(); a.desc=string.format("HALion Sonic initialisiert: %d Instanzspur(en), %d Slot(s)",tr,sl); diag_set("halion_result",a.desc) elseif a.kind=="TRANSPOSE" then local take=a.item.take; local _,nc=reaper.MIDI_CountEvts(take); for i=0,(nc or 0)-1 do local yes,sel,mut,s,e,ch,p,v=reaper.MIDI_GetNote(take,i); if yes and not mut then local np=p+a.n; if np<0 or np>127 then error("Transposition würde den MIDI-Bereich verlassen.") end; reaper.MIDI_SetNote(take,i,sel,mut,s,e,ch,np,v,true) end end; reaper.MIDI_Sort(take) elseif a.kind=="MOVE_ITEM" then local pos=reaper.GetMediaItemInfo_Value(a.item.item,"D_POSITION"); local qn=reaper.TimeMap2_timeToQN(0,pos)+a.q; if qn<0 then error("Item würde vor Projektbeginn liegen.") end; reaper.SetMediaItemInfo_Value(a.item.item,"D_POSITION",reaper.TimeMap2_QNToTime(0,qn)) elseif a.kind=="COPY_ITEM" then local src=a.item.item; local okc,chunk=reaper.GetItemStateChunk(src,"",false); if not okc then error("Item konnte nicht gelesen werden.") end; local ni=reaper.AddMediaItemToTrack(a.item.track); if not reaper.SetItemStateChunk(ni,chunk,false) then error("Item konnte nicht kopiert werden.") end; local qn=reaper.TimeMap2_timeToQN(0,reaper.GetMediaItemInfo_Value(src,"D_POSITION"))+a.q; if qn<0 then error("Kopie würde vor Projektbeginn liegen.") end; reaper.SetMediaItemInfo_Value(ni,"D_POSITION",reaper.TimeMap2_QNToTime(0,qn)); reaper.SetMediaItemSelected(ni,true) elseif a.kind=="RENAME_TRACK" then reaper.GetSetMediaTrackInfo_String(a.track,"P_NAME",a.name,true) end end,debug.traceback); if not ok then reaper.Undo_EndBlock2(0,"Composition Studio – fehlgeschlagen",-1); reaper.Undo_DoUndo2(0); return nil,err end; reaper.UpdateArrange(); reaper.Undo_EndBlock2(0,"Composition Studio – "..a.kind,-1); return true end
local function parse_notes(text) local notes={}; for t in (text or ""):gmatch("[^;]+") do local a,b,c,d,e=t:match("^%s*([%d%.%-]+),([%d%.%-]+),(%d+),(%d+),(%d+)%s*$"); a,b,c,d,e=tonumber(a),tonumber(b),tonumber(c),tonumber(d),tonumber(e); if not(a and b and c and d and e) then return nil end; notes[#notes+1]={start_qn=a,duration_qn=b,pitch=c,velocity=d,channel=e} end; return #notes>0 and notes or nil end
local function create_track(name,index) index=index or reaper.CountTracks(0); reaper.InsertTrackAtIndex(index,true); local t=reaper.GetTrack(0,index); if t then reaper.GetSetMediaTrackInfo_String(t,"P_NAME",name,true) end; return t end
local function existing_program(track) for i=0,reaper.CountTrackMediaItems(track)-1 do local item=reaper.GetTrackMediaItem(track,i); local take=item and reaper.GetActiveTake(item); if take and reaper.TakeIsMIDI(take) then local _,_,_,cc=reaper.MIDI_CountEvts(take); for n=0,(cc or 0)-1 do local ok,_,muted,_,chanmsg,_,msg2=reaper.MIDI_GetCC(take,n); if ok and not muted and chanmsg==0xC0 then return msg2 end end end end; return nil end
local function program_for_name(name,proposed) local n=(name or ""):lower(); local map={{"violin",40},{"violine",40},{"geige",40},{"viola",41},{"bratsche",41},{"cello",42},{"violoncello",42},{"kontrabass",43},{"double bass",43},{"gitarre",24},{"guitar",24},{"harfe",46},{"harp",46},{"flöte",73},{"floete",73},{"flute",73},{"oboe",68},{"klarinette",71},{"clarinet",71},{"fagott",70},{"bassoon",70},{"trompete",56},{"trumpet",56},{"horn",60},{"posaune",57},{"trombone",57},{"sax",65},{"klavier",0},{"piano",0},{"orgel",19},{"organ",19}}; for _,p in ipairs(map) do if n:find(p[1],1,true) then return p[2] end end; local v=tonumber(proposed); if v and v>=0 and v<=127 then return math.floor(v) end; return 0 end
local function create_midi(track,name,notes,program) local lo,hi=math.huge,-math.huge; for _,n in ipairs(notes) do lo=math.min(lo,n.start_qn); hi=math.max(hi,n.start_qn+n.duration_qn) end; if hi<=lo then return nil end; local item=reaper.CreateNewMIDIItemInProj(track,reaper.TimeMap2_QNToTime(0,lo),reaper.TimeMap2_QNToTime(0,hi),false); local take=item and reaper.GetActiveTake(item); if not take then return nil end; reaper.GetSetMediaItemTakeInfo_String(take,"P_NAME",name,true); local ch=math.max(0,math.min(15,(notes[1].channel or 0))); local ppq=reaper.MIDI_GetPPQPosFromProjTime(take,reaper.TimeMap2_QNToTime(0,lo)); local pg=math.max(0,math.min(127,program or 0)); reaper.MIDI_InsertCC(take,false,false,ppq,0xB0,ch,0,0); reaper.MIDI_InsertCC(take,false,false,ppq,0xB0,ch,32,0); reaper.MIDI_InsertCC(take,false,false,ppq,0xC0,ch,pg,0); for _,n in ipairs(notes) do local s=reaper.MIDI_GetPPQPosFromProjTime(take,reaper.TimeMap2_QNToTime(0,n.start_qn)); local e=reaper.MIDI_GetPPQPosFromProjTime(take,reaper.TimeMap2_QNToTime(0,n.start_qn+n.duration_qn)); reaper.MIDI_InsertNote(take,false,false,s,e,n.channel,n.pitch,n.velocity,true) end; reaper.MIDI_Sort(take); return item end
local function apply_composition(text,items,tracks) local src,targets={},{ }; for _,it in ipairs(items) do src[it.guid]=it end; for _,t in ipairs(tracks or {}) do targets[t.guid]=t.track end; local jobs={}; for line in text:gmatch("[^\r\n]+") do local k,g,rest=trim(line):match("^CS|([^|]+)|([^|]+)|?(.*)$"); if not k then return nil,"Unerwartete Kompositionsantwort." end; if k=="unchanged" then if not src[g] then return nil,"Unbekannte Quelle." end elseif k=="revised" or k=="target" or k=="track" or k=="new" then local name,pg,nt=rest:match("^([^|]+)|(%d+)|(.+)$"); local notes=parse_notes(nt); local program=tonumber(pg); if not name or not notes or not program or program<0 or program>127 then return nil,"Ungültige Kompositionsdaten." end; if (k=="revised" or k=="target") and not src[g] then return nil,"Unbekannte Quelle." end; if k=="track" and not targets[g] then return nil,"Unbekannte Zielspur." end; if k=="new" and g~="-" then return nil,"Ungültige neue Spur." end; jobs[#jobs+1]={kind=k,guid=g,name=trim(name),program=program_for_name(name,program),notes=notes} else return nil,"Unbekannter Ergebnistyp." end end; reaper.Undo_BeginBlock2(0); local made={}; local ok,err=xpcall(function() for _,j in ipairs(jobs) do local tr; if j.kind=="revised" then local no=math.floor(reaper.GetMediaTrackInfo_Value(src[j.guid].track,"IP_TRACKNUMBER")); tr=create_track(j.name.." [Variante]",no) elseif j.kind=="target" then tr=src[j.guid].track elseif j.kind=="track" then tr=targets[j.guid] else tr=create_track(j.name) end; local inherited=(j.kind~="new") and existing_program(tr) or nil; local it=create_midi(tr,j.name,j.notes,inherited or j.program); if not it then error("MIDI konnte nicht erzeugt werden") end; made[#made+1]=it end end,debug.traceback); if not ok then reaper.Undo_EndBlock2(0,"Composition Studio – fehlgeschlagen",-1); reaper.Undo_DoUndo2(0); return nil,err end; reaper.UpdateArrange(); reaper.Undo_EndBlock2(0,"Composition Studio – KI-Komposition",-1); return made end
local function analysis_prompt(request,items,tracks) return [[Du analysierst das konkret übergebene MIDI-Material. Antworte musikalisch präzise als normaler Text. Erfinde nichts. Erzeuge kein MIDI und keine CS-Zeilen.]].."\nAUFTRAG:\n"..request.."\nMUSIK:\n"..music_context(items,tracks) end
local function composition_prompt(request,items,tracks) return [[Du komponierst Musik in Composition Studio. Nutze vorhandenes Material als musikalischen Kontext und erfülle den freien Auftrag eigenständig; füge keine unnötigen Regeln hinzu. Wenn weder MIDI-Material noch eine Zielspur vorhanden ist, handelt es sich bei einem entsprechenden Auftrag um eine freie Neukomposition: Erzeuge die benötigten neuen Spuren mit CS|new. TIME_SELECTION ist der markierte Zielbereich. Eine ausgewählte TRACK_GUID kann auch ohne ausgewähltes MIDI-Item direkt Ziel sein. Jedes neu erzeugte MIDI-Item MUSS einen passenden General-MIDI-Program-Change (0-127) erhalten. Verwende für benannte Instrumente den passenden GM-Wert, z.B. Violine=40, Cello=42, akustische Gitarre=24. Bei vorhandenen Zielspuren wird ein dort bereits vorhandener Program Change von Composition Studio bevorzugt übernommen.
Antworte ausschließlich:
CS|unchanged|SOURCE_GUID
CS|target|SOURCE_GUID|NAME|PROGRAM|startQN,durationQN,pitch,velocity,channel;...
CS|track|TRACK_GUID|NAME|PROGRAM|startQN,durationQN,pitch,velocity,channel;...
CS|revised|SOURCE_GUID|NAME|PROGRAM|startQN,durationQN,pitch,velocity,channel;...
CS|new|-|NAME|PROGRAM|startQN,durationQN,pitch,velocity,channel;...
PROGRAM ist die GM-Programmnummer 0-127. Nutze track bei einer ausdrücklich ausgewählten Zielspur, target bei der Spur eines ausgewählten Quell-Items, new für eine neue Stimme/Spur und revised für eine separate Variante. Bei einer freien Neukomposition mit mehreren Instrumenten erzeuge für jedes Instrument eine eigene CS|new-Zeile.]].."\nAUFTRAG:\n"..request.."\nMUSIK:\n"..music_context(items,tracks) end
local function process(request) last_diag={version=VERSION,request=request}; local key=get_key(); if not key then add("KI","Kein OpenAI API-Key verfügbar."); return end; local items=selected_items(false); local tracks=selected_tracks(); diag_set("context",compact_context(items,tracks)); local prompt=CONTROLLER.."\n\nBISHERIGER DIALOG:\n"..recent_dialog().."\n\nAKTUELLER AUFTRAG:\n"..request.."\n\nKOMPAKTER REAPER-KONTEXT:\n"..compact_context(items,tracks); diag_set("controller_prompt",prompt); local answer,err=run_openai(prompt,key); diag_set("controller_answer",answer or err or ""); if not answer then add("KI",err); return end; answer=trim(answer); local chat=answer:match("^CHAT|(.*)$"); if chat then add("KI",trim(chat)); return end; local ask=answer:match("^ASK|(.*)$"); if ask then add("KI",trim(ask)); return end; local awhy=answer:match("^NEED_ANALYSIS|(.*)$"); if awhy then local full=selected_items(true); if #full==0 and #tracks>0 then full=track_context_items(tracks) end; if #full==0 then add("KI","Für die Analyse ist kein MIDI-Material ausgewählt."); return end; local text,e=run_openai(analysis_prompt(request,full,tracks),key); if not text then add("KI",e); return end; add("KI",trim(text)); return end; local newwhy=answer:match("^NEED_NEW|(.*)$"); local why=answer:match("^NEED_MUSIC|(.*)$"); if newwhy or why then local full=newwhy and {} or selected_items(true); if newwhy then tracks={} end; if #full==0 and #tracks>0 then full=track_context_items(tracks) end; local cp=composition_prompt(request,full,tracks); diag_set("composition_prompt",cp); local comp,e=run_openai(cp,key); diag_set("composition_answer",comp or e or ""); if not comp then add("KI",e); return end; local made,ae=apply_composition(comp,full,tracks); diag_set("apply_result",made and ("created_items="..tostring(#made)) or ("ERROR: "..tostring(ae))); if not made then add("KI","Die musikalische Antwort konnte nicht sicher angewendet werden: "..tostring(ae)); return end; local htr,hsl=initialize_halion_project(); diag_set("halion_result",string.format("auto_initialized_tracks=%d slots=%d",htr,hsl)); add("KI",string.format("Erledigt. %d neues bzw. überarbeitetes MIDI-Item wurde erzeugt.",#made)); return end; if answer:match("^ACTION|") then local a,e=parse_action(answer,items); if not a then add("KI","Ich führe nichts aus: "..e); return end; local ok,ae=execute_action(a); if not ok then add("KI","Die Aktion wurde nicht ausgeführt: "..tostring(ae)); return end; add("KI",trim(a.desc).." – erledigt. REAPER Undo kann die Änderung rückgängig machen."); return end; add("KI","Ich konnte den Auftrag nicht eindeutig einem sicheren Vorgang zuordnen und habe nichts verändert.") end
local function submit() local r=trim(input); if r=="" or busy then return end; input=""; info_visible=false; history_mode=false; add("Du",r); busy=true; process(r); busy=false end
local function wrap_text(s,limit) limit=math.max(12,math.floor(limit or 40)); local out={}; for line in (tostring(s or "").."\n"):gmatch("(.-)\n") do while #line>limit do local cut=limit; local part=line:sub(1,limit); local sp=part:match("^.*()%s+"); if sp and sp>math.floor(limit*0.55) then cut=sp end; out[#out+1]=line:sub(1,cut):gsub("%s+$",""); line=line:sub(cut+1):gsub("^%s+","") end; out[#out+1]=line end; return table.concat(out,"\n"):gsub("\n$","") end
local function info_text() return "AKTUELLER STAND\n\nComposition Studio arbeitet direkt in REAPER.\n\nWAS IST NEU? – "..VERSION.."\n\n• Nach erfolgreicher MIDI-Erzeugung wird HALion Sonic automatisch einmalig aus den ersten Program Changes der direkt aufliegenden bzw. hineingerouteten MIDI-Spuren initialisiert.\n• Kanal 1–16 wird einmalig auf S1–S16 Program Change übertragen.\n• Es werden KEINE dauerhaften MIDI-Links erzeugt; HALion bleibt danach frei manuell bedienbar.\n• Program Changes mitten im laufenden Stück werden in 0.4 noch nicht live verfolgt.\n• Die vorhandenen MIDI-Program-Changes bleiben unverändert erhalten.\n• Diagnose speichert den letzten vollständigen Vorgang als JSON.\n• Die übrige Kompositionslogik bleibt unverändert." end
local function draw_history() if info_visible then reaper.ImGui_TextWrapped(ctx,info_text()); return end; local flags=0; if type(reaper.ImGui_InputTextFlags_ReadOnly)=="function" then flags=flags|reaper.ImGui_InputTextFlags_ReadOnly() end; if type(reaper.ImGui_InputTextFlags_NoHorizontalScroll)=="function" then flags=flags|reaper.ImGui_InputTextFlags_NoHorizontalScroll() end; local avail=select(1,reaper.ImGui_GetContentRegionAvail(ctx)); local limit=math.max(18,math.floor((avail-24)/9.5)); for i=chat_start,#history do local m=history[i]; reaper.ImGui_Text(ctx,m.role..":"); local text=wrap_text(m.text or "",limit); local lines=1; for _ in text:gmatch("\n") do lines=lines+1 end; local height=math.max(48,math.min(260,lines*22+12)); reaper.ImGui_InputTextMultiline(ctx,"##chatmsg"..i,text,-1,height,flags); reaper.ImGui_Spacing(ctx) end; if history_mode then reaper.ImGui_Separator(ctx); if reaper.ImGui_Button(ctx,"Verlauf löschen") then clear_saved_history() end end end
local function remember_closed() save_history(); reaper.SetExtState(EXT_SECTION,WINDOW_STATE_KEY,"0",true) end
local function check_project_change() local p=reaper.EnumProjects(-1,""); if p~=current_project then save_history(current_project); current_project=p; load_history(current_project) end end
local function loop() if not open then if not restarting then remember_closed() end; return end; check_project_change(); reaper.ImGui_SetNextWindowSize(ctx,360,620,reaper.ImGui_Cond_FirstUseEver()); local visible; visible,open=reaper.ImGui_Begin(ctx,SCRIPT_NAME.."###CompositionStudioMain",open); if visible then local pushed=push_font(); local items=selected_items(false); local tracks=selected_tracks(); reaper.ImGui_Text(ctx,SCRIPT_NAME.."  "..VERSION); reaper.ImGui_SameLine(ctx); if reaper.ImGui_Button(ctx,"Info") then info_visible=true; history_mode=false end; reaper.ImGui_SameLine(ctx); if reaper.ImGui_Button(ctx,"Diagnose") then save_diagnosis() end; reaper.ImGui_SameLine(ctx); if reaper.ImGui_Button(ctx,"Update") then install_update() end; reaper.ImGui_Text(ctx,string.format("GPT-5.6  |  %d MIDI-Item(s) | %d Spur(en) ausgewählt",#items,#tracks)); if update_status~="" then reaper.ImGui_TextWrapped(ctx,update_status) end; reaper.ImGui_Separator(ctx); local w,h=reaper.ImGui_GetContentRegionAvail(ctx); local ih,bh=112,32; local ch=math.max(120,h-ih-bh*2-84); if reaper.ImGui_BeginChild(ctx,"##chat",w,ch,reaper.ImGui_ChildFlags_Borders()) then draw_history(); reaper.ImGui_EndChild(ctx) end; reaper.ImGui_Spacing(ctx); local input_flags=0; if type(reaper.ImGui_InputTextFlags_NoHorizontalScroll)=="function" then input_flags=input_flags|reaper.ImGui_InputTextFlags_NoHorizontalScroll() end; local changed,v=reaper.ImGui_InputTextMultiline(ctx,"##request",input,w,ih,input_flags); if changed then input=wrap_text(v,58) end; reaper.ImGui_Spacing(ctx); local gap=6; local bw=math.max(110,(w-gap)/2); if reaper.ImGui_Button(ctx,busy and "Warten…" or "Senden",bw,bh) and not busy then submit() end; reaper.ImGui_SameLine(ctx,0,gap); if reaper.ImGui_Button(ctx,"Verlauf",bw,bh) then chat_start=1; info_visible=false; history_mode=true end; if reaper.ImGui_Button(ctx,"Chat leeren",bw,bh) then chat_start=#history+1; info_visible=false; history_mode=false end; reaper.ImGui_SameLine(ctx,0,gap); if reaper.ImGui_Button(ctx,"Schließen",bw,bh) then open=false end; pop_font(pushed); reaper.ImGui_End(ctx) end; if open then reaper.defer(loop) elseif not restarting then remember_closed() end end
loop()